---
title: "Brexit"
output: html_notebook
---


```{r, echo = FALSE}
library(tidyverse)
dat <- read.csv("data/voter_type_data.csv")
dat$voter_type <- factor(dat$voter_type, levels = c("0.Stay/remain in the EU", 
                                                    "1.Stay/remain in the EU", 
                                                    "1.Leave the EU",
                                                    "0.Leave the EU",
                                                    "0.Don't know",
                                                    "1.Don't know"))
dat$headHouseholdPast<-plyr::revalue(as.factor(dat$headHouseholdPast), 
                                        c("1"="My father", "2"="My mother", 
                                          "3" = "Someone else",
                                          "4" = "No one in my house worked",
                                          "9999" = "Don't know"))
```
### Why 'ifswitch' intead of 'switch_ratio':
Firstly, the proportion is highly skewed
```{r}
table(dat$ifswitch)
# 0     1 
# 48327 20298 
```

Distribution of the switch_ratio looks like:
```{r echo = FALSE}
dat %>%
  ggplot(aes(switch_ratio)) + geom_histogram(binwidth = 0.03)
```

Without looking at voters who never switched:
```{r echo = FALSE}
# NOTE: bin width: 0.5 peaked!
dat %>%
  filter(switch_ratio!=0) %>%
  ggplot(aes(switch_ratio)) + geom_histogram(binwidth = 0.02)
```

Secondly, immigration sentiment appears consistent irrespective of switch_ratio

```{r echo = FALSE}
dat %>%
  filter(switch_ratio!=0) %>%
  ggplot(aes(x = as.factor(switch_ratio), y = immig_index5)) + geom_boxplot() +
  xlab("Switch Ratio Amongst 'Switchers'") + ylab("Anti-immigrant Sentiment Index")+
  scale_x_discrete(breaks=c(0:1))
```

### Distribution of immigration sentiment across public
```{R echo = FALSE}

dat %>%
  ggplot(aes(immig_index5)) + geom_histogram(binwidth = 0.02)
```

